<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="gen_base" params="x:=0 y:=0 z:=0 radius:=0.2 lenght:=0.2 wheel_radius:=0.05">
    <link name="base_link">
      <visual>
        <origin xyz="${x} ${y} ${z + 2*wheel_radius + (lenght/2)}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${radius}" length="${lenght}"/>
        </geometry>
        <material name="grey"/>
      </visual>
    </link>

    <link name="front_wheel">
      <visual name="">
        <origin xyz="${x+(radius/3)} ${y} ${z+wheel_radius}" rpy="${pi/2} 0.0 0.0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.01"/>
        </geometry>
        <material name="blue"/>
      </visual>
    </link>

    <link name="left_wheel">
      <visual name="">
        <origin xyz="${x-(radius/3)} ${y+(radius/3)} ${z+wheel_radius}" rpy="${pi/2} 0.0 0.0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.01"/>
        </geometry>
        <material name="blue"/>
      </visual>
    </link>

    <link name="rigth_wheel">
      <visual name="">
        <origin xyz="${x-(radius/3)} ${y-(radius/3)} ${z+wheel_radius}" rpy="${pi/2} 0.0 0.0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.01"/>
        </geometry>
        <material name="blue"/>
      </visual>
    </link>

    <xacro:include filename="bumper.xacro"/>
    <xacro:gen_bumper x="${x}" y="${y}" z="${z + 2*wheel_radius + (lenght/2)}" radius="${radius+0.025}"/>

  </xacro:macro>
</robot>