<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


<xacro:macro name="gen_body" params="x:=0 y:=0 z:=0 radius:=0.2 lenght:=0.4 ir_len:=0.1 sonar_len:=0.1">
  <xacro:include filename="ir.xacro"/>
  <xacro:gen_ir x="${x}" y="${y}" z="${z}" radius="${radius}" lenght="${ir_len}"/>

  <link name="link_name">
    <visual name="">
      <origin xyz="${x} ${y} ${z + ir_len +(lenght/2)}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${radius}" length="${lenght}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <xacro:include filename="sonar.xacro"/>
  <xacro:gen_sonar x="${x}" y="${y}"  radius="${radius}" lenght="${sonar_len}" z="${z+ ir_len +(lenght)}"/>

</xacro:macro>

</robot>