<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="elements" value="16"/>
  <xacro:macro name="sensor_base" params="base_name:=sensor x:=0 y:=0 z:=0 radius:=0.2 lenght:=0.1 elements:=${elements} s_material:=Black b_material:=Orange **geometry_sensor **geometry_base ">
    <xacro:macro name="generate_sensor" params="index">
      <xacro:if value="${index}">
        <link name="${base_name}_${index}_link">
          <xacro:property name="rotation" value="${2*pi*index/elements}"/>
          <xacro:property name="x_axis" value="${radius*cos(rotation)}" />
          <xacro:property name="y_axis" value="${radius*sin(rotation)}" />
          <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}" />
            <geometry>
              <xacro:insert_block name="geometry_sensor"/>
            </geometry>
            <material name="${s_material}"/>
          </visual>
        </link>
        <!-- Create joins -->
        <joint name="${base_name}_${index}" type="fixed">
          <parent link="${base_name}_link"/>
          <child link="${base_name}_${index}_link"/>
          <origin xyz="${x_axis} ${y_axis} 0" rpy="0 0 ${rotation}"/>
        </joint>
        <!--${pi/2} 0 ${rotation+(pi/2)}-->
        <!--  loop -->
        <xacro:generate_sensor index="${index-1}" />
      </xacro:if>
    </xacro:macro>
    <link name="${base_name}_link">
      <visual name="">
        <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <xacro:insert_block name="geometry_base"/>
        </geometry>
        <material name="${b_material}"/>
      </visual>
    </link>
    <xacro:generate_sensor index="${elements}"/>
  </xacro:macro>
</robot>